<?php
/**
 * Created by PhpStorm.
 * User: bolotkalil
 * Date: 11/18/18
 * Time: 12:15 AM
 */

namespace PatternDesigns\Creational\Singleton;


use PHPUnit\Framework\TestCase;
use PHPUnit\Runner\Exception;

class SingletonTest extends TestCase
{
    /**
     * @var Singleton
     */
    private $singleton;

    public function setUp()/* The :void return type declaration that should be here would cause a BC issue */
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->singleton = Singleton::getInstance();
    }

    /**
     * @expectedException \Error
     */
    public function testSingletonClone()
    {
        $newInstance = clone $this->singleton;
    }

    /**
     * @expectedException \Error
     */
    public function testSingleton()
    {
        $newObject = new Singleton();
    }

    public function testInstance()
    {
        $this->assertInstanceOf(Singleton::class, Singleton::getInstance());
    }
}