<?php
/**
 * Created by PhpStorm.
 * User: bolotkalil
 * Date: 11/20/18
 * Time: 8:16 PM
 */

namespace PatternDesigns\Behavioral\State;


use PHPUnit\Framework\TestCase;

class StateTest extends TestCase
{
    public function setUp()/* The :void return type declaration that should be here would cause a BC issue */
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testState()
    {
        $state = new State(new NormalBattery());
        $this->assertEquals('forward', $state->execute('go'));
        $this->assertEquals('stopped', $state->execute('stop'));
        $state->setState(new LowBattery());
        $this->assertEquals(null, $state->execute('go'));
    }
}