<?php
/**
 * Created by PhpStorm.
 * User: bolotkalil
 * Date: 11/20/18
 * Time: 2:56 PM
 */

namespace PatternDesigns\Behavioral\Command;


use PHPUnit\Framework\TestCase;

class CommandTest extends TestCase
{
    /**
     * @var Command
     */
    private $command;
    public function setUp()/* The :void return type declaration that should be here would cause a BC issue */
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->command = new Command(new Receiver());
    }

    public function testReceiver()
    {
        $this->assertEquals('receiver test', $this->command->execute());
    }

}