<?php

namespace PatternDesigns\Creational\FactoryMethod;

use \PHPUnit\Framework\TestCase;

class FactoryMethodTest extends TestCase
{
    /**
     * @var FactoryMethod
     */
    private $factoryMethod;

    public function setUp()/* The :void return type declaration that should be here would cause a BC issue */
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->factoryMethod = new FactoryMethod();
    }

    public function testFactory()
    {
        $factory = $this->factoryMethod->getFactory('PatternDesigns\Creational\FactoryMethod\ProductA');
        $this->assertEquals('Product A', $factory->someOperation());

        $factory = $this->factoryMethod->getFactory('PatternDesigns\Creational\FactoryMethod\ProductB');
        $this->assertEquals('Product B', $factory->someOperation());
    }
}